### ISSUE TITLE
i can't run the shell scripts

### ISSUE THREAD

**Issue by herbertchen1** [wikilinks/neleval#31]
sudo sh ./scripts/run_tac15_evaluation.sh /home/cb/eval/mentions_gold_name.xml /home/cb/eval/tac_kbp_2015_tedl_evaluation_gold_standard_entity_mentions.tab  /home/cb/output /home/cb/evalre

i dont know what are the whole arguments? 
Where can I find a readable introduction of the  arguments?
 this is the message happened when i try to run the scripts:
INFO Converting gold to evaluation format..
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/neleval/__main__.py", line 91, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/neleval/__main__.py", line 86, in main
    result = obj()
  File "/usr/local/lib/python2.7/dist-packages/neleval/tac.py", line 193, in __call__
    return u'\n'.join(unicode(a) for a in self.read_annotations(self.system))
  File "/usr/local/lib/python2.7/dist-packages/neleval/tac.py", line 193, in <genexpr>
    return u'\n'.join(unicode(a) for a in self.read_annotations(self.system))
  File "/usr/local/lib/python2.7/dist-packages/neleval/tac.py", line 212, in read_annotations
    key=key_fn), key_fn)
IndexError: list index out of range
INFO converting systems to evaluation format..
ls: cannot access /home/cb/eval/tac_kbp_2015_tedl_evaluation_gold_standard_entity_mentions.tab/*: Not a directory
xargs: invalid number for -P option
Usage: xargs [-0prtx] [--interactive] [--null] [-d|--delimiter=delim]
       [-E eof-str] [-e[eof-str]]  [--eof[=eof-str]]
       [-L max-lines] [-l[max-lines]] [--max-lines[=max-lines]]
       [-I replace-str] [-i[replace-str]] [--replace[=replace-str]]
       [-n max-args] [--max-args=max-args]
       [-s max-chars] [--max-chars=max-chars]
       [-P max-procs]  [--max-procs=max-procs] [--show-limits]
       [--verbose] [--exit] [--no-run-if-empty] [--arg-file=file]
       [--version] [--help] [command [initial-arguments]]

**Comment by jnothman** [comment]
running `./scripts/run_tac15_evaluation.sh` will print:
```
Usage: scripts/run_tac15_all.sh GOLD SYSTEMS_DIR OUT_DIR [-x EXCLUDED_SPANS]
```

You've provided a file, not a directory of system outputs.
